package de.upb.crypto.craco.abe.cp.large;

import de.upb.crypto.craco.common.WatersHash;
import de.upb.crypto.math.factory.BilinearGroup;
import de.upb.crypto.math.factory.BilinearGroupFactory;
import de.upb.crypto.math.interfaces.hash.HashIntoStructure;
import de.upb.crypto.math.structures.zn.Zp;
import de.upb.crypto.math.structures.zn.Zp.ZpElement;

public class ABECPWat11Setup {
    private ABECPWat11PublicParameters pp;
    private ABECPWat11MasterSecret msk;

    /**
     * Generate public parameters and the master secret.
     * <p>
     * Sets up public parameters and the master secret for a given security parameter
     * securityParameter. The parameter n specifies the maximum number of
     * attributes per key. The parameter l_max specifies the maximum number of
     * rows per MSPs. The parameter watersHash selects between two possible hash
     * functions: Waters Hash function or the hash function from the group
     * factory. The former yields a secure construction in the standard model
     * while the latter might be only secure in the random oracle model.
     * Typically, setting watersHash to false provides much faster
     * implementations, especially for large n and l_max.
     * <p>
     * To enable debugging modus, set debug to true. WARNING: This results in an
     * insecure instantiation of the underlying groups.
     *
     * @param securityParameter
     * @param n                 - maximum number of attributes per key.
     * @param l_max             - maxium number of rows per MSP
     * @param watersHash        - the hash function
     * @param debug             - enable debugging.
     */
    public void doKeyGen(int securityParameter, int n, int l_max, boolean watersHash, boolean debug) {
        // Generate bilinear group
        BilinearGroupFactory fac = new BilinearGroupFactory(securityParameter);
        fac.setDebugMode(debug);
        fac.setRequirements(BilinearGroup.Type.TYPE_1, !watersHash, false, false);
        BilinearGroup group = fac.createBilinearGroup();

        doKeyGen(group, n, l_max, watersHash);
    }

    /**
     * Setup with Waters Hash function. Secure in standard model.
     *
     * @param securityParameter
     * @param n                 - maximum number of attributes per key
     * @param l_max             - maximum size of MSP
     */
    public void doKeyGenWatersHash(int securityParameter, int n, int l_max) {
        doKeyGen(securityParameter, n, l_max, true, false);
    }

    /**
     * Setup with cryptographic hash function. Secure in random oracle model.
     *
     * @param securityParameter
     */
    public void doKeyGenRandomOracle(int securityParameter) {
        doKeyGen(securityParameter, Integer.MAX_VALUE / 2, Integer.MAX_VALUE / 2, false, false);
    }

    /**
     * Setup with a pre-made group
     *
     * @param group group used for the scheme
     * @param n     maximum number of attributes per key
     * @param lMax  maximum size of MSP
     */
    public void doKeyGen(BilinearGroup group, int n, int lMax, boolean watersHash) {
        pp = new ABECPWat11PublicParameters();

        pp.setN(n);
        pp.setL_max(lMax);

        pp.setGroupG1(group.getG1());
        pp.setGroupGT(group.getGT());
        if (!watersHash) {
            pp.setHashToG1(group.getHashIntoG1());
        } else {
            HashIntoStructure hashToGroup = new WatersHash(pp.getGroupG1(), n + lMax);
            pp.setHashToG1(hashToGroup);
        }
        pp.setE(group.getBilinearMap());

        Zp zp = new Zp(pp.getGroupG1().size());

        // Do the scheme setup stuff
        ZpElement y = zp.getUniformlyRandomUnit();
        ZpElement a = zp.getUniformlyRandomUnit();
        pp.setG(pp.getGroupG1().getUniformlyRandomNonNeutral());
        // Y = e(g,g)^y = e(g^y, g)
        pp.setY(pp.getE().apply(pp.getG().pow(y), pp.getG()));
        pp.setG_a(pp.getG().pow(a));
        msk = new ABECPWat11MasterSecret(pp.getG().pow(y));
    }

    /**
     * Returns the public parameter generated by {@link #doKeyGen} or null if no
     * public parameters were generated
     *
     * @return the public parameters that can be used for setting up the {@link ABECPWat11}
     */
    public ABECPWat11PublicParameters getPublicParameters() {
        return pp;
    }

    /**
     * The master secret of this scheme. This is needed for generating a {@link ABECPWat11DecryptionKey} in the
     * {@link ABECPWat11}
     *
     * @return
     */
    public ABECPWat11MasterSecret getMasterSecret() {
        return msk;
    }
}
