package de.upb.crypto.craco.abe.fuzzy.large;

import de.upb.crypto.craco.interfaces.EncryptionKey;
import de.upb.crypto.math.hash.annotations.AnnotatedUbrUtil;
import de.upb.crypto.math.hash.annotations.UniqueByteRepresented;
import de.upb.crypto.math.interfaces.hash.ByteAccumulator;
import de.upb.crypto.math.serialization.Representation;
import de.upb.crypto.math.serialization.annotations.AnnotatedRepresentationUtil;
import de.upb.crypto.math.serialization.annotations.Represented;

/**
 * An {@link EncryptionKey} for the {@link IBEFuzzySW05}. The Key
 * is generated by
 * {@link IBEFuzzySW05#generateEncryptionKey(Identity)}
 *
 * @author Mirko Jürgens
 */
public class IBEFuzzySW05EncryptionKey implements EncryptionKey {

    @UniqueByteRepresented
    @Represented
    private Identity identity;

    public IBEFuzzySW05EncryptionKey(Identity id) {
        this.identity = id;
    }

    public IBEFuzzySW05EncryptionKey(Representation repr) {
        AnnotatedRepresentationUtil.restoreAnnotatedRepresentation(repr, this);
    }

    @Override
    public Representation getRepresentation() {
        return AnnotatedRepresentationUtil.putAnnotatedRepresentation(this);
    }

    /**
     * Getter for {@link #identity}
     *
     * @return the encryption's key identity
     */
    public Identity getIdentity() {
        return identity;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((identity == null) ? 0 : identity.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        IBEFuzzySW05EncryptionKey other = (IBEFuzzySW05EncryptionKey) obj;
        if (identity == null) {
            if (other.identity != null)
                return false;
        } else if (!identity.getAttributes().containsAll(other.identity.getAttributes())
                || !other.identity.getAttributes().containsAll(identity.getAttributes()))
            return false;
        return true;
    }

    @Override
    public ByteAccumulator updateAccumulator(ByteAccumulator accumulator) {
        return AnnotatedUbrUtil.autoAccumulate(accumulator, this);
    }

}
